server:
  port: 7777

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}/youtube
    username: postgres
    password: postgres
    platform: postgresql
    initialization-mode: never
    name: youtube
    continue-on-error: true

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    drop-first: false
    enabled: true
  session:
    store-type: jdbc

logging:
  level:
    root: info
    org.springframework:
      web: debug
      security: off
      session: off
    ru.itfb.elib: debug
    org:
      hibernate:
        type: trace